import { HexCluster, Match } from "./types";

export const DEMO_INTENT = "anyone want to play pickleball in the Mission in the next hour?";

export const MOCK_ELAPSED_MS = 11;

export const mockMatches: Match[] = [
  {
    id: "m1",
    displayName: "Priya K.",
    avatarColor: "#F97316",
    activityLabel: "Pickleball",
    requestedActivity: "pickleball",
    rawText: "down to play pickleball at Dolores Park courts, flexible on time",
    distanceM: 420,
    overlapMinutes: 55,
    trustScore: 4.6,
    score: 0.94,
  },
  {
    id: "m2",
    displayName: "Marcus T.",
    avatarColor: "#0EA5E9",
    activityLabel: "Tennis",
    requestedActivity: "tennis",
    adjacencyPath: ["pickleball", "racquet sports", "tennis"],
    rawText: "anyone want to hit tennis balls, total beginner",
    distanceM: 780,
    overlapMinutes: 40,
    trustScore: 4.2,
    score: 0.81,
  },
  {
    id: "m3",
    displayName: "Lin W.",
    avatarColor: "#22C55E",
    activityLabel: "Badminton",
    requestedActivity: "badminton",
    adjacencyPath: ["pickleball", "racquet sports", "badminton"],
    rawText: "looking for a badminton partner this evening, indoors ok",
    distanceM: 1100,
    overlapMinutes: 30,
    sharedLanguage: "Mandarin",
    trustScore: 4.8,
    score: 0.77,
  },
  {
    id: "m4",
    displayName: "Sofia R.",
    avatarColor: "#A855F7",
    activityLabel: "Pickleball",
    requestedActivity: "pickleball",
    rawText: "same, need one more for doubles at Mission Rec",
    distanceM: 300,
    overlapMinutes: 60,
    sharedLanguage: "Spanish",
    trustScore: 4.9,
    score: 0.92,
  },
  {
    id: "m5",
    displayName: "Grace C.",
    avatarColor: "#EAB308",
    activityLabel: "Companionship visit",
    requestedActivity: "companionship visit",
    rawText: "would love company for tea this afternoon, I'm in Chinatown",
    distanceM: 3400,
    overlapMinutes: 90,
    sharedLanguage: "Cantonese",
    trustScore: 4.7,
    score: 0.38,
    isSenior: true,
    verifiedOrg: "Chinatown Senior Center",
  },
];

export const hexClusters: HexCluster[] = [
  { id: "mission", name: "Mission", lat: 37.7599, lon: -122.4148, matched: 210, unmatched: 18 },
  { id: "soma", name: "SoMa", lat: 37.7785, lon: -122.4056, matched: 175, unmatched: 22 },
  { id: "marina", name: "Marina", lat: 37.8021, lon: -122.4382, matched: 160, unmatched: 15 },
  { id: "hayes-valley", name: "Hayes Valley", lat: 37.7765, lon: -122.4241, matched: 140, unmatched: 20 },
  { id: "north-beach", name: "North Beach", lat: 37.8000, lon: -122.4100, matched: 95, unmatched: 60 },
  { id: "inner-sunset", name: "Inner Sunset", lat: 37.7601, lon: -122.4685, matched: 88, unmatched: 55 },
  { id: "inner-richmond", name: "Inner Richmond", lat: 37.7802, lon: -122.4644, matched: 90, unmatched: 58 },
  {
    id: "chinatown",
    name: "Chinatown",
    lat: 37.7941,
    lon: -122.4078,
    matched: 24,
    unmatched: 130,
    gapNote: "71% of companionship requests unanswered, most in Cantonese, weekday afternoons.",
  },
  {
    id: "tenderloin",
    name: "Tenderloin",
    lat: 37.7840,
    lon: -122.4144,
    matched: 20,
    unmatched: 115,
    gapNote: "Care and mobility requests go unmatched more than any other neighborhood.",
  },
  {
    id: "bayview",
    name: "Bayview",
    lat: 37.7299,
    lon: -122.3900,
    matched: 18,
    unmatched: 108,
    gapNote: "Ride-to-appointment requests are the most common unmatched need.",
  },
  {
    id: "excelsior",
    name: "Excelsior",
    lat: 37.7244,
    lon: -122.4300,
    matched: 22,
    unmatched: 96,
    gapNote: "Senior social and household-help requests dominate the unmatched queue.",
  },
  {
    id: "sf-state",
    name: "SF State / Parkmerced",
    lat: 37.7241,
    lon: -122.4799,
    matched: 70,
    unmatched: 35,
    gapNote: "Campus micro-needs (chargers, textbooks) spike late afternoon.",
  },
];
